# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: build
  build:
    cmds:
      - go build
    sources:
      - ./*.go
    generates:
      - excel2pdf{{exeExt}}
    method: timestamp
  clean:
    cmds:
      - go clean
      - cmd /c "rd /s /q .task"
